name: Build addon
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*"
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Set up Python (for SCons)
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Linux dependencies
        if: ${{ matrix.platform == 'linux' }}
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y zip        # for zipping release artifacts
          sudo apt-get install -qqq build-essential pkg-config libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev
      - name: Install scons
        run: |
          python -m pip install scons==4.0.0
      - name: Setup MinGW for Windows/MinGW build
        if: ${{ matrix.platform == 'windows' && matrix.flags == 'use_mingw=yes' }}
        uses: egor-tensin/setup-mingw@v2

      - name: Build godot-cpp
        if: ${{ env.FAST_BUILD != 'true' }}
        run: |
          pushd godot-cpp
          scons platform=windows target=debug
          scons platform=windows target=release
          scons platform=linux   target=debug
          scons platform=linux   target=release
          popd

      - name: build delaunator Windows
        continue-on-error: true
        run: |
          scons platform=windows target=release bits=64 target_name="gddelaunator" target_path="./demo/addons/delaunator_gdextension/bin/"
          scons platform=windows target=debug   bits=64 target_name="gddelaunator" target_path="./demo/addons/delaunator_gdextension/bin/"

      - name: build delaunator Linux debug
        run: |
          scons platform=linux target=debug   bits=64 target_name="gddelaunator" target_path="./demo/addons/delaunator_gdextension/bin/"
          scons platform=linux target=release bits=64 target_name="gddelaunator" target_path="./demo/addons/delaunator_gdextension/bin/"

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: delaunator_gdextension
          path: demo

      - name: zip artifacts for release
        run: |
          pushd demo
          zip ../delaunator_gdextension.zip addons/* -r
          popd

      - name: Publish release
        continue-on-error: true # the step will fail if build wasn't triggered by a tag
        uses: softprops/action-gh-release@v1
        with:
          # note you'll typically need to create a personal access token
          # with permissions to create releases in the other repo
          token: ${{ secrets.RELEASE_TOKEN }}
          files: delaunator_gdextension.zip
